"""
config.py  –  Central configuration for the OpenDSS → pandapower pipeline.

Edit only this file to switch networks or change top-level paths.
All other scripts import from here instead of using hardcoded strings.
"""
from pathlib import Path

# ─── PROJECT ROOT (resolved relative to this file) ────────────────────────────
PROJECT_ROOT = Path(__file__).parent.resolve()

# ─── NETWORK SELECTION ────────────────────────────────────────────────────────
# Options: "1"=Rural_SMR8  "2"=Rural_KLO14  "3"=Urban_HPK11  "4"=Urban_CRE21
NETWORK_OPTION = "2"
NET_DIR_NAMES = {
    "1": "net_1_Rural_SMR8",
    "2": "net_2_Rural_KLO14",
    "3": "net_3_Urban_HPK11",
    "4": "net_4_Urban_CRE21",
}
_NET_SUBDIR = NET_DIR_NAMES[NETWORK_OPTION]
SELECTED_DAY   = 15    # 0 = random (seeded), 1..365 = fixed day of year
SEED           = 100
TIME_RES_MIN   = 30    # minutes per timestep (48 steps = 1 day at 30-min resolution)

# ─── DIRECTORIES ──────────────────────────────────────────────────────────────
EXCELS_DIR   = PROJECT_ROOT / "excels"
DSS_DIR      = PROJECT_ROOT / "dss_files"
PROFILES_DIR = PROJECT_ROOT / "profiles"   # legacy; generated profiles go to DSS_DIR/profiles
RESULTS_DIR  = PROJECT_ROOT / "results" / _NET_SUBDIR
METRICS_DIR  = PROJECT_ROOT / "metrics"             # script source folder
METRICS_OUT_DIR = PROJECT_ROOT / "metrics" / _NET_SUBDIR  # per-network output

# ─── NETWORK EXCEL INPUT FILES ────────────────────────────────────────────────
NETWORK_XLSX_MAP = {
    "1": EXCELS_DIR / "Network_1_Rural_SMR8.xlsx",
    "2": EXCELS_DIR / "Network_2_Rural_KLO14.xlsx",
    "3": EXCELS_DIR / "Network_3_Urban_HPK11.xlsx",
    "4": EXCELS_DIR / "Network_4_Urban_CRE21.xlsx",
}
NETWORK_XLSX = NETWORK_XLSX_MAP[NETWORK_OPTION]

RES_PROFILE_NPY = EXCELS_DIR / "Res_load_data_30min_res.npy"
COM_PROFILE_NPY = EXCELS_DIR / "Com_load_data_30min_res.npy"

# ─── DSS FILES (generated by dss_files_creator, consumed by conversion scripts)
CIRCUIT_DSS    = DSS_DIR / "01_Circuit.dss"
LINECODES_DSS  = DSS_DIR / "03_LineCodes.dss"
MV_LINES_DSS   = DSS_DIR / "04_MV_Lines.dss"
CAPS_DSS       = DSS_DIR / "05_Capacitors.dss"
REGS_DSS       = DSS_DIR / "06_Regulators.dss"
LV_TX_DSS      = DSS_DIR / "07_LV_Tx.dss"
LV_LINES_DSS   = DSS_DIR / "08_LV_Lines.dss"
LOADSHAPES_DSS = DSS_DIR / "09_LoadShapes.dss"
LOADS_DSS      = DSS_DIR / "10_Loads.dss"
BUSCOORDS_CSV  = DSS_DIR / "BusCoords.csv"
MV_NETTX_DSS   = DSS_DIR / "02_MV_NetTx.dss"

# ─── REGULATOR sn_mva OVERRIDES (per network) ────────────────────────────────
# Keys = base regulator name (without _A/_B/_C suffix), values = sn_mva in MVA.
# Used when DSS kVA is a per-phase stub value and the real rating is known.
# Leave empty ({}) to rely entirely on the DSS kVA value.
REG_SN_MVA_MAP = {
    "1": {
        "NAGAMBIE_REGULATOR": 5.0,
        "AVENEL_REGULATOR":   2.5,
    },
    "2": {},  # read automatically from '! regulator_kva' comments in 06_Regulators.dss
    "3": {},
    "4": {},
}
REG_SN_MVA_OVERRIDES = REG_SN_MVA_MAP.get(NETWORK_OPTION, {})

# base_dir used by parse_loadshapes_dss() to resolve relative CSV paths
# (paths in 09_LoadShapes.dss look like "profiles/Load_shape_X.csv",
#  so base_dir must point to the directory that contains the profiles/ sub-folder)
LOADSHAPES_BASE_DIR = DSS_DIR

# ─── INTERMEDIATE / OUTPUT NETWORK FILES ──────────────────────────────────────
MV_NET_XLSX  = DSS_DIR / "mv_net.xlsx"
NET_PP_XLSX  = DSS_DIR / "net_pp.xlsx"
NET_3PH_XLSX = DSS_DIR / "net_pp_3ph_ready.xlsx"
NET_3PH_JSON = DSS_DIR / "net_pp_3ph_ready.json"

# ─── RESULTS ──────────────────────────────────────────────────────────────────
RESULTS_RES_BUS     = RESULTS_DIR / "res_bus"
RESULTS_RES_BUS_3PH = RESULTS_DIR / "res_bus_3ph"
RESULTS_RES_LINE    = RESULTS_DIR / "res_line"
RESULTS_RES_TRAFO   = RESULTS_DIR / "res_trafo"
RESULTS_RES_LOAD    = RESULTS_DIR / "res_load"

# ─── METRICS / VALIDATION ─────────────────────────────────────────────────────
# DSS reference results (produced by nando_runs, compared in metrics/)
DSS_VM_PU_XLSX    = EXCELS_DIR / "vm_pu_1ph_equivalent.xlsx"
DSS_VM_PU_SHEET   = "vm_pu"
DSS_VDATA_CLEAN   = EXCELS_DIR / "Vdata_all_buses_clean.csv"   # raw Volts, col=bus.phase
# DSS balanced (1-phase equivalent) line loading reference
DSS_LINE_LOADING_CSV    = EXCELS_DIR / "all_lines_loading_percent.csv"
# DSS balanced mean-per-bus vm_pu CSV (produced by nando_run_balanced.py)
DSS_VM_MEAN_PU_CSV      = EXCELS_DIR / "Vmean_vm_pu_with_source.csv"
DSS_MV_LINE_LOADING_XLSX  = EXCELS_DIR / "mv_line_loading.xlsx"
DSS_MV_LINE_LOADING_SHEET = "loading_pct"

PLOTS_DIR = PROJECT_ROOT / "plots"
METRIC_PER_BUS    = METRICS_OUT_DIR / "metric_per_bus.csv"
METRIC_GLOBAL_TXT = METRICS_OUT_DIR / "metric_global.txt"
METRIC_3PH_PER_BUS    = METRICS_OUT_DIR / "metric_3ph_per_bus.csv"
METRIC_3PH_GLOBAL_TXT = METRICS_OUT_DIR / "metric_3ph_global.txt"

# DSS 3ph reference loading (produced by nando_1_timeseries_3ph_loading.py)
DSS_LINE_LOADING_A  = EXCELS_DIR / "dss_line_loading_a_percent.csv"
DSS_LINE_LOADING_B  = EXCELS_DIR / "dss_line_loading_b_percent.csv"
DSS_LINE_LOADING_C  = EXCELS_DIR / "dss_line_loading_c_percent.csv"
DSS_TRAFO_LOADING_A = EXCELS_DIR / "dss_trafo_loading_a_percent.csv"
DSS_TRAFO_LOADING_B = EXCELS_DIR / "dss_trafo_loading_b_percent.csv"
DSS_TRAFO_LOADING_C = EXCELS_DIR / "dss_trafo_loading_c_percent.csv"
# 1-phase line-to-line trafos (HV connected between two phases, no neutral on HV)
# pandapower's runpp_3ph cannot model these correctly → excluded from loading metrics
# DSS balanced (1-phase equivalent) trafo loading reference
DSS_TRAFO_LOADING_XLSX  = EXCELS_DIR / "trafos_dss.xlsx"
DSS_TRAFO_LOADING_SHEET = "loading_percent"

DSS_TRAFO_LL_NAMES    = EXCELS_DIR / "dss_trafo_line_to_line_names.csv"
# 1-phase Wye-Wye (pole-top) trafos (HV phase-to-neutral, single-phase)
# PP models them as 3-phase Dyn → single-phase-only load causes solver divergence
DSS_TRAFO_1PH_YY_NAMES = EXCELS_DIR / "dss_trafo_1ph_yy_names.csv"
